Repository halo-sigs/plugin-hybrid-edit-block, pull requests merged in 2024-07, with the labels that each got.

#15 fix: incorrect homepage in plugin.yaml
  src/main/resources/plugin.yaml
Labels: lgtm, release-note-none, approved

#14 pref: XSS filtering to prevent execution of malicious code in editor
  console/package.json
  console/pnpm-lock.yaml
  console/src/editor/code-mirror-view.ts
Labels: kind/improvement, lgtm, release-note, approved

#17 chore: cleanup deprecated constructor for base plugin
  src/main/java/run/halo/editor/HybridEditBlockPlugin.java
Labels: lgtm, release-note, kind/cleanup, approved
